name: deploy
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            BUILD_DIR_PATH: build
            DEPLOY_BRANCH: gh-pages
        steps:
            - uses: actions/checkout@v2
            - run: |
                npm install
                git checkout --orphan $DEPLOY_BRANCH
                git config --local user.email "action@github.com"
                git config --local user.name "Github Action"
                git config --local core.worktree $(pwd)/$BUILD_DIR_PATH
                git add -A
                git commit -m "Auto-deploy $GITHUB_SHA"      
            - uses: ad-m/github-deploy-actions@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ env.DEPLOY_BRANCH }}
                force: true
      